name: stopwatch
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/blackandwhite.jpg
    - assets/autumn.jpg
    - assets/galaxy.jpeg
    - assets/mermaid.jpg
    - assets/home.jpg
  fonts:
    - family: FragileBombers
      fonts:
        - asset: fonts/Fragile Bombers.otf
    - family: FragileBombersAttack
      fonts:
        - asset: fonts/Fragile Bombers Attack.otf
    - family: FragileBombersDown
      fonts:
        - asset: fonts/Fragile Bombers Down.otf
    - family: LeagueGothic
      fonts:
        - asset: fonts/LeagueGothic-Regular.otf
        - asset: fonts/LeagueGothic-Italic.otf
          style: italic
    - family: LeagueGothicCondensed
      fonts:
        - asset: fonts/LeagueGothic-CondensedRegular.otf
        - asset: fonts/LeagueGothic-CondensedItalic.otf
          style: italic
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron Light.ttf
          weight: 300
        - asset: fonts/Orbitron Medium.ttf
          weight: 500
        - asset: fonts/Orbitron Bold.ttf
          weight: 700
        - asset: fonts/Orbitron Black.ttf
          weight: 900
    - family: HistoryOfWawa
      fonts:
        - asset: fonts/History of Wawa.otf
